In [76]:
import numpy as np
import pandas as pd

In [77]:
df = pd.read_csv("/content/Employee.csv")
df

    Emp_ID            Name   Age Department   Salary  Experience_Years
0      101      Anish Pote  25.0         IT  55000.0               3.0
1      102  Tanishq Bharti  28.0         HR  60000.0               5.0
2      103   Piyush Ahirao   NaN    Finance  72000.0               8.0
3      104  Durvas Bhadane  29.0         IT      NaN               4.0
4      105    Shivam Kumar  27.0      Sales  50000.0               NaN
5      106  Vaibhav Dudhal  26.0  Marketing  48000.0               2.0
6      107      Manish Rai  34.0         HR  65000.0              10.0
7      108      Neha Joshi  31.0         IT  70000.0               6.0
8      109     Arjun Verma  30.0      Sales      NaN               5.0
9      110    Pooja Sharma   NaN    Finance  75000.0              11.0
10     111      Anish Pote  25.0         IT  55000.0               3.0
11     112       Vinay Rao  27.0  Marketing  47000.0               3.0
12     113     Komal Desai  33.0    Finance  72000.0               NaN
13     114      Amit Patil  25.0         IT  50000.0               2.0
14     115      Seema Rani  36.0         HR      NaN              15.0
15     116     Deepak Nair  32.0      Sales  53000.0               7.0
16     117     Rahul Gupta  29.0         IT  60000.0               5.0
17     118     Meena Gupta  26.0  Marketing  48000.0               2.0
18     119   Manish Tiwari  38.0    Finance  80000.0               NaN
19     120     Anjali Jain  31.0         HR  64000.0               9.0

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Emp_ID            20 non-null     int64
 1   Name              20 non-null     object
 2   Age               18 non-null     float64
 3   Department        20 non-null     object
 4   Salary            17 non-null     float64
 5   Experience_Years  17 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.1+ KB

In [79]:
df.describe()

          Emp_ID        Age        Salary  Experience_Years
count   20.00000  18.000000     17.000000         17.000000
mean   110.50000  29.555556  60235.294118          5.882353
std      5.91608   3.899053  10633.258036          3.689213
min    101.00000  25.000000  47000.000000          2.000000
25%    105.75000  26.250000  50000.000000          3.000000
50%    110.50000  29.000000  60000.000000          5.000000
75%    115.25000  31.750000  70000.000000          8.000000
max    120.00000  38.000000  80000.000000         15.000000

In [80]:
df.head()

   Emp_ID            Name   Age Department   Salary  Experience_Years
0     101      Anish Pote  25.0         IT  55000.0               3.0
1     102  Tanishq Bharti  28.0         HR  60000.0               5.0
2     103   Piyush Ahirao   NaN    Finance  72000.0               8.0
3     104  Durvas Bhadane  29.0         IT      NaN               4.0
4     105    Shivam Kumar  27.0      Sales  50000.0               NaN

In [81]:
df.tail()

    Emp_ID           Name   Age Department   Salary  Experience_Years
15     116    Deepak Nair  32.0      Sales  53000.0               7.0
16     117    Rahul Gupta  29.0         IT  60000.0               5.0
17     118    Meena Gupta  26.0  Marketing  48000.0               2.0
18     119  Manish Tiwari  38.0    Finance  80000.0               NaN
19     120    Anjali Jain  31.0         HR  64000.0               9.0

In [82]:
df.isnull()

    Emp_ID   Name    Age  Department  Salary  Experience_Years
0    False  False  False       False   False             False
1    False  False  False       False   False             False
2    False  False   True       False   False             False
3    False  False  False       False    True             False
4    False  False  False       False   False              True
5    False  False  False       False   False             False
6    False  False  False       False   False             False
7    False  False  False       False   False             False
8    False  False  False       False    True             False
9    False  False   True       False   False             False
10   False  False  False       False   False             False
11   False  False  False       False   False             False
12   False  False  False       False   False              True
13   False  False  False       False   False             False
14   False  False  False       False    True             False
15   False  False  False       False   False             False
16   False  False  False       False   False             False
17   False  False  False       False   False             False
18   False  False  False       False   False              True
19   False  False  False       False   False             False

In [83]:
df.isnull().sum()

Emp_ID              0
Name                0
Age                 2
Department          0
Salary              3
Experience_Years    3
dtype: int64

In [84]:
df = df.drop_duplicates(subset=['Name', 'Age', 'Department', 'Salary', 'Experience_Years'])

In [85]:
df

    Emp_ID            Name   Age Department   Salary  Experience_Years
0      101      Anish Pote  25.0         IT  55000.0               3.0
1      102  Tanishq Bharti  28.0         HR  60000.0               5.0
2      103   Piyush Ahirao   NaN    Finance  72000.0               8.0
3      104  Durvas Bhadane  29.0         IT      NaN               4.0
4      105    Shivam Kumar  27.0      Sales  50000.0               NaN
5      106  Vaibhav Dudhal  26.0  Marketing  48000.0               2.0
6      107      Manish Rai  34.0         HR  65000.0              10.0
7      108      Neha Joshi  31.0         IT  70000.0               6.0
8      109     Arjun Verma  30.0      Sales      NaN               5.0
9      110    Pooja Sharma   NaN    Finance  75000.0              11.0
11     112       Vinay Rao  27.0  Marketing  47000.0               3.0
12     113     Komal Desai  33.0    Finance  72000.0               NaN
13     114      Amit Patil  25.0         IT  50000.0               2.0
14     115      Seema Rani  36.0         HR      NaN              15.0
15     116     Deepak Nair  32.0      Sales  53000.0               7.0
16     117     Rahul Gupta  29.0         IT  60000.0               5.0
17     118     Meena Gupta  26.0  Marketing  48000.0               2.0
18     119   Manish Tiwari  38.0    Finance  80000.0               NaN
19     120     Anjali Jain  31.0         HR  64000.0               9.0

In [86]:
df = df.drop_duplicates(subset=['Name', 'Age', 'Department', 'Salary', 'Experience_Years']).reset_index(drop=True)
df

    Emp_ID            Name   Age Department   Salary  Experience_Years
0      101      Anish Pote  25.0         IT  55000.0               3.0
1      102  Tanishq Bharti  28.0         HR  60000.0               5.0
2      103   Piyush Ahirao   NaN    Finance  72000.0               8.0
3      104  Durvas Bhadane  29.0         IT      NaN               4.0
4      105    Shivam Kumar  27.0      Sales  50000.0               NaN
5      106  Vaibhav Dudhal  26.0  Marketing  48000.0               2.0
6      107      Manish Rai  34.0         HR  65000.0              10.0
7      108      Neha Joshi  31.0         IT  70000.0               6.0
8      109     Arjun Verma  30.0      Sales      NaN               5.0
9      110    Pooja Sharma   NaN    Finance  75000.0              11.0
10     112       Vinay Rao  27.0  Marketing  47000.0               3.0
11     113     Komal Desai  33.0    Finance  72000.0               NaN
12     114      Amit Patil  25.0         IT  50000.0               2.0
13     115      Seema Rani  36.0         HR      NaN              15.0
14     116     Deepak Nair  32.0      Sales  53000.0               7.0
15     117     Rahul Gupta  29.0         IT  60000.0               5.0
16     118     Meena Gupta  26.0  Marketing  48000.0               2.0
17     119   Manish Tiwari  38.0    Finance  80000.0               NaN
18     120     Anjali Jain  31.0         HR  64000.0               9.0

In [91]:
df['Age'].fillna(df['Age'].mean())
df['Salary'].fillna(df['Salary'].mean())
df['Experience_Years'].fillna(df['Experience_Years'].mean())
df

    Emp_ID            Name        Age Department   Salary  Experience_Years
0      101      Anish Pote  25.000000         IT  55000.0            3.0000
1      102  Tanishq Bharti  28.000000         HR  60000.0            5.0000
2      103   Piyush Ahirao  29.823529    Finance  72000.0            8.0000
3      104  Durvas Bhadane  29.000000         IT  60562.5            4.0000
4      105    Shivam Kumar  27.000000      Sales  50000.0            6.0625
5      106  Vaibhav Dudhal  26.000000  Marketing  48000.0            2.0000
6      107      Manish Rai  34.000000         HR  65000.0           10.0000
7      108      Neha Joshi  31.000000         IT  70000.0            6.0000
8      109     Arjun Verma  30.000000      Sales  60562.5            5.0000
9      110    Pooja Sharma  29.823529    Finance  75000.0           11.0000
10     112       Vinay Rao  27.000000  Marketing  47000.0            3.0000
11     113     Komal Desai  33.000000    Finance  72000.0            6.0625
12     114      Amit Patil  25.000000         IT  50000.0            2.0000
13     115      Seema Rani  36.000000         HR  60562.5           15.0000
14     116     Deepak Nair  32.000000      Sales  53000.0            7.0000
15     117     Rahul Gupta  29.000000         IT  60000.0            5.0000
16     118     Meena Gupta  26.000000  Marketing  48000.0            2.0000
17     119   Manish Tiwari  38.000000    Finance  80000.0            6.0625
18     120     Anjali Jain  31.000000         HR  64000.0            9.0000

In [93]:
df_minmax = df.copy()
for col in ['Age', 'Salary', 'Experience_Years']:
    df_minmax[col] = (df_minmax[col] - df_minmax[col].min()) / (df_minmax[col].max() - df_minmax[col].min())
df_minmax

    Emp_ID            Name       Age Department    Salary  Experience_Years
0      101      Anish Pote  0.000000         IT  0.242424          0.076923
1      102  Tanishq Bharti  0.230769         HR  0.393939          0.230769
2      103   Piyush Ahirao  0.371041    Finance  0.757576          0.461538
3      104  Durvas Bhadane  0.307692         IT  0.410985          0.153846
4      105    Shivam Kumar  0.153846      Sales  0.090909          0.312500
5      106  Vaibhav Dudhal  0.076923  Marketing  0.030303          0.000000
6      107      Manish Rai  0.692308         HR  0.545455          0.615385
7      108      Neha Joshi  0.461538         IT  0.696970          0.307692
8      109     Arjun Verma  0.384615      Sales  0.410985          0.230769
9      110    Pooja Sharma  0.371041    Finance  0.848485          0.692308
10     112       Vinay Rao  0.153846  Marketing  0.000000          0.076923
11     113     Komal Desai  0.615385    Finance  0.757576          0.312500
12     114      Amit Patil  0.000000         IT  0.090909          0.000000
13     115      Seema Rani  0.846154         HR  0.410985          1.000000
14     116     Deepak Nair  0.538462      Sales  0.181818          0.384615
15     117     Rahul Gupta  0.307692         IT  0.393939          0.230769
16     118     Meena Gupta  0.076923  Marketing  0.030303          0.000000
17     119   Manish Tiwari  1.000000    Finance  1.000000          0.312500
18     120     Anjali Jain  0.461538         HR  0.515152          0.538462

In [96]:
print("\n Central Tendency:")
print("Mean:\n", df[['Age', 'Salary', 'Experience_Years']].mean())
print("Median:\n", df[['Age', 'Salary', 'Experience_Years']].median())
print("Mode:\n", df[['Age', 'Salary', 'Experience_Years']].mode().iloc[0])

 Central Tendency:
Mean:
 Age                    29.823529
Salary              60562.500000
Experience_Years        6.062500
dtype: float64
Median:
 Age                    29.823529
Salary              60562.500000
Experience_Years        6.000000
dtype: float64
Mode:
 Age                    25.0
Salary              60562.5
Experience_Years        2.0
Name: 0, dtype: float64

In [97]:
print("\n📊 Dispersion:")
print("Variance:\n", df[['Age', 'Salary', 'Experience_Years']].var())
print("Standard Deviation:\n", df[['Age', 'Salary', 'Experience_Years']].std())
print("Range:\n", df[['Age', 'Salary', 'Experience_Years']].max() - df[['Age', 'Salary', 'Experience_Years']].min())

📊 Dispersion:
Variance:
 Age                 1.313725e+01
Salary              9.888542e+07
Experience_Years    1.160764e+01
dtype: float64
Standard Deviation:
 Age                    3.624535
Salary              9944.114675
Experience_Years       3.406999
dtype: float64
Range:
 Age                    13.0
Salary              33000.0
Experience_Years       13.0
dtype: float64